import type {Restaurant, MenuItem} from '@/types/database';

const baseRestaurantFields = {
  is_seed_data: true,
  approval_status: 'approved',
  is_featured: false,
  is_accepting_orders: true,
  accepting_start_time: null,
  accepting_end_time: null,
  owner_id: null,
  address: null,
  latitude: null,
  longitude: null,
  delivery_radius_km: null,
  image_url: null,
} as const;

export const mockRestaurants: Restaurant[] = [
  {
    ...baseRestaurantFields,
    id: '1',
    name: "Mama Ngozi's Kitchen",
    slug: 'mama-ngozi-kitchen',
    category: 'Local & Native',
    rating: 4.8,
    delivery_time_min: 15,
    delivery_time_max: 20,
    zone: 'Awka',
    is_open: true,
    is_promoted: true,
    is_featured: true,
    created_at: new Date().toISOString(),
  },
  {
    ...baseRestaurantFields,
    id: '2',
    name: 'Suya Republic',
    slug: 'suya-republic',
    category: 'Fast food',
    rating: 4.6,
    delivery_time_min: 20,
    delivery_time_max: 25,
    zone: 'Awka',
    is_open: true,
    is_promoted: true,
    is_featured: true,
    created_at: new Date().toISOString(),
  },
  {
    ...baseRestaurantFields,
    id: '3',
    name: 'Green Bowl Smoothies',
    slug: 'green-bowl-smoothies',
    category: 'Drinks & snacks',
    rating: 4.9,
    delivery_time_min: 10,
    delivery_time_max: 15,
    zone: 'Awka',
    is_open: true,
    is_promoted: true,
    is_featured: true,
    created_at: new Date().toISOString(),
  },
  {
    ...baseRestaurantFields,
    id: '4',
    name: 'Chop Point',
    slug: 'chop-point',
    category: 'Fast food',
    rating: 4.4,
    delivery_time_min: 18,
    delivery_time_max: 22,
    zone: 'Onitsha',
    is_open: false,
    is_promoted: false,
    is_accepting_orders: false,
    created_at: new Date().toISOString(),
  },
  {
    ...baseRestaurantFields,
    id: '5',
    name: 'Pepper Soup Palace',
    slug: 'pepper-soup-palace',
    category: 'Local & Native',
    rating: 4.7,
    delivery_time_min: 25,
    delivery_time_max: 35,
    zone: 'Nnewi',
    is_open: true,
    is_promoted: false,
    created_at: new Date().toISOString(),
  },
];

export const mockMenuItems: MenuItem[] = [
  {
    id: 'm1',
    restaurant_id: '1',
    name: 'Jollof Rice & Chicken',
    price: 2500,
    category: 'Popular',
    image_url: null,
    is_seed_data: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'm2',
    restaurant_id: '1',
    name: 'Ofe Nsala with Fufu',
    price: 3200,
    category: 'Soups',
    image_url: null,
    is_seed_data: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'm3',
    restaurant_id: '1',
    name: 'Fried Rice & Turkey',
    price: 2800,
    category: 'Rice dishes',
    image_url: null,
    is_seed_data: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'm4',
    restaurant_id: '1',
    name: 'Zobo Drink',
    price: 700,
    category: 'Drinks',
    image_url: null,
    is_seed_data: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'm5',
    restaurant_id: '1',
    name: 'Egusi Soup & Pounded Yam',
    price: 3500,
    category: 'Soups',
    image_url: null,
    is_seed_data: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'm6',
    restaurant_id: '1',
    name: 'African Salad',
    price: 1800,
    category: 'Popular',
    image_url: null,
    is_seed_data: true,
    created_at: new Date().toISOString(),
  },
];
